version: '3'

services:

  traefik:
    image: "traefik:v2.0.1"
    container_name: "traefik"
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file=true
      - --providers.file.filname=/dynamic.toml
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:cached
      - ./dynamic.toml:/dynamic.toml:cached

  nginx:
    build: ./nginx
    container_name: "nginx"
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./logs/api:/var/www/app/var/log:cached
      - ./app/:/var/www/app:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`docker.dev.localhost`)"
      - "traefik.nginx.port=80"
      - "traefik.nginx.port=443"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.https.tls=true"

  php:
    build: ./php
    container_name: "php"
    expose:
      - 9001
    links:
      - db
    volumes:
      - ./app:/var/www/app:cached
    labels:
      - "traefik.enable=true"
      - "traefik.php.port=9001"
      - "traefik.http.routers.php.entrypoints=http"
      - "traefik.https.routers.php.entrypoints=https"

  db:
    image: mysql
    container_name: "db"
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    labels:
      - "traefik.enable=false"
      - "traefik.db.port=3306"
