version: '3'
services:
    traefik:
        image: "traefik:v2.0.1"
        container_name: "traefik"
        command:
            - --api.insecure=true
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --global.checkNewVersion=true
            - --global.sendAnonymousUsage=false
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
