version: '3'

services:

  php-app:
    build: ./php
    container_name: "php-app"
    networks:
        - docker-web
    links:
      - db-app
    volumes:
      - ./app:/var/www/app:cached
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker-web"

      - "traefik.http.routers.php-app.rule=Host(`docker.app.localhost`)"
      - "traefik.http.routers.php-app.entrypoints=websecure"
      - "traefik.http.routers.php-app.tls=true"
      - "traefik.http.routers.php-app.tls.certresolver=leresolver"
    # user: "1000:1001"

  db-app:
    image: mysql
    container_name: "db-app"
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    labels:
      - "traefik.enable=false"

networks:
  docker-web:
      external: true
