version: '3'

services:

  php-app:
    build: ./php
    container_name: "app-php"
    networks:
      - dockymfik-network
    depends_on:
      - app-db
    volumes:
      - ./app:/var/www/app:cached
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dockymfik-network"

      - "traefik.http.routers.php-app.rule=Host(`docker.app.localhost`)"
      - "traefik.http.routers.php-app.entrypoints=websecure"
      - "traefik.http.routers.php-app.tls=true"
      - "traefik.http.routers.php-app.tls.certresolver=leresolver"
    environment:
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      APP_ENV: "${APP_ENV}"
      DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@app-db:3306/db"

      STARTUP_COMMAND_1: composer install
      STARTUP_COMMAND_2: echo 'alias sf="php bin/console"' >> ~/.bashrc
      # STARTUP_COMMAND_3: yqrn install & yarn build
    restart: unless-stopped

  app-db:
    image: mysql:5.7
    container_name: "app-db"
    networks:
      - dockymfik-network
    env_file:
      - ./../.env
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    labels:
      - "traefik.enable=true"
    restart: unless-stopped

networks:
  dockymfik-network:
      external: true
